#!/bin/sh

# Hide the mouse cursor
unclutter -idle 0.01 -root &

# Start Chromium in kiosk mode with hardware acceleration
chromium \
    --no-sandbox \
    --kiosk \
    --disable-translate \
    --no-first-run \
    --disable-infobars \
    --disable-session-crashed-bubble \
    --ignore-gpu-blocklist \
    --enable-gpu-rasterization \
    --enable-zero-copy \
    --enable-features=VaapiVideoDecoder \
    --use-gl=angle \
    --enable-unsafe-webgpu \
    "${KIOSK_URL}" &