#!/bin/bash

# Hide the mouse cursor
unclutter -idle 0.01 -root &

# Start Chromium in kiosk mode
#
# --- KEY CHANGES ---
# REMOVED: --enable-features=UseRkmppDecode (Your kernel driver is broken)
# ADDED:   Flags to disable video acceleration attempts and properly enable GPU for UI
# -----------------
/usr/bin/chromium \
    --no-sandbox \
    --kiosk \
    --ignore-gpu-blocklist \
    --in-process-gpu \
    --use-gl=egl \
    --enable-gpu-rasterization \
    --enable-zero-copy \
    --disable-features=VaapiVideoDecoder \
    --disable-accelerated-video-decode \
    $KIOSK_URL