#!/bin/bash

# Hide the mouse cursor
unclutter -idle 0.01 -root &

# Start Chromium in kiosk mode with hardware acceleration
/usr/bin/chromium \
    --no-sandbox \
    --kiosk \
    --ignore-gpu-blocklist \
    --use-gl=egl \
    --enable-features=UseRkmppDecode \
    --disable-features=Vulkan,UseSkiaRenderer \
    --in-process-gpu \
    $KIOSK_URL